# Generated by Django 4.2 on 2024-07-21 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_options_products_image_products_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
