# Generated by Django 4.2.14 on 2024-07-26 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_products_buyers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='buyers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
